# https://travis-ci.org/spyder-ide/spyder

language: generic
dist: trusty
sudo: false
env:
  global:
    - CI_PYTEST: "true"

matrix:
  fast_finish: true
  include:
    - env: PYTHON_VERSION=2.7 USE_CONDA=yes
    - env: PYTHON_VERSION=3.6 USE_CONDA=yes
    - env: PYTHON_VERSION=3.7 USE_CONDA=yes
    - env: PYTHON_VERSION=3.6 USE_CONDA=no
    - env: PYTHON_VERSION=3.7 USE_CONDA=no

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Avoid annoying focus problems when running tests
  # See discussion in e.g. https://github.com/spyder-ide/spyder/pull/6132
  - sudo apt-get -qq update
  - sudo apt-get install -y matchbox-window-manager
  - matchbox-window-manager&
  - sleep 5

install:
  - ./continuous_integration/travis/install.sh

script:
  - ./continuous_integration/travis/runtests.sh || ./continuous_integration/travis/runtests.sh || ./continuous_integration/travis/runtests.sh

after_success:
  - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate test && coveralls
