# https://ci.appveyor.com/project/spyder-ide/spyder

environment:

  global:
    PYTHON: "C:\\Miniconda36-x64"
    APPVEYOR_RDP_PASSWORD: "dcca4c4863E30d56c2e0dda6327370b3#"

  matrix:
    - PYTHON_VERSION: "3.6"
    - PYTHON_VERSION: "2.7"

platform:
  -x64

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "conda create -y -n test python=%PYTHON_VERSION%"
  - "activate test"
  - "conda install -q -y -c spyder-ide --file requirements/conda.txt"
  - "conda install -q -y -c spyder-ide --file requirements/tests.txt"
  # Pin to pyqt 5.6 until we figure it out how to fix our tests with 5.9
  - "if %PYTHON_VERSION%==3.6 conda install -y -q pyqt=5.6*"
  # Reinstall Matplotlib in case it had been removed
  - "if %PYTHON_VERSION%==3.6 conda install -y -q --no-deps matplotlib"
  # Install spyder-kernels from Github
  - "pip install -q --no-deps git+https://github.com/spyder-ide/spyder-kernels"
  # Install codecov
  - "pip install -q codecov"

build: false

test_script:
  # Run tests only once in Python 2 and exit because I don't know why they are failing.
  - if %PYTHON_VERSION%==2.7 (python runtests.py || exit 0) else (python runtests.py || python runtests.py || python runtests.py)

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_success:
#  - codecov
