# https://ci.appveyor.com/project/spyder-ide/spyder

environment:

  global:
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "latest"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
    PYTHON_ARCH: "64"
    PIP_DEPENDENCIES_FLAGS: "-q"
    CONDA_DEPENDENCIES_FLAGS: "--quiet"
    CONDA_DEPENDENCIES: >
      rope pyflakes sphinx pygments pylint pycodestyle psutil nbconvert
      qtawesome cloudpickle pickleshare pyzmq chardet mock pandas pytest
      pytest-cov numpydoc scipy pillow qtconsole matplotlib jedi pywin32
      sympy cython keyring
    PIP_DEPENDENCIES: >
      pytest-qt pytest-mock flaky codecov
      python-language-server[all] qdarkstyle
    APPVEYOR_RDP_PASSWORD: "dcca4c4863E30d56c2e0dda6327370b3#"

  matrix:
    - PYTHON_VERSION: "2.7"
    - PYTHON_VERSION: "3.6"

platform:
  -x64

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  # Install qtpy from Github
  - "pip install git+https://github.com/spyder-ide/qtpy.git"
  # Fix problems with latest pyqt
  - "conda install pyqt=5.6*"
  # Reinstall Matplotlib in case it had been removed
  - "conda install --no-deps matplotlib"
  # Install spyder-kernels from Github
  - "pip install -q --no-deps git+https://github.com/spyder-ide/spyder-kernels"

build: false

test_script:
  # Run tests only once in Python 2 and exit because I don't know why they are failing.
  - if %PYTHON_VERSION%==2.7 (%CMD_IN_ENV% python runtests.py || exit 0) else (%CMD_IN_ENV% python runtests.py || %CMD_IN_ENV% python runtests.py || %CMD_IN_ENV% python runtests.py)

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_success:
  - codecov
